### ISSUE TITLE
ngtcp2 v1 release plan

### ISSUE THREAD

**Issue by tatsuhiro-t** [ngtcp2/ngtcp2#777]
## Prerequisites

The following QUIC extensions drafts are published as RFC:

- [x] https://datatracker.ietf.org/doc/html/draft-ietf-quic-version-negotiation -> https://datatracker.ietf.org/doc/html/rfc9368
- [x] https://datatracker.ietf.org/doc/html/draft-ietf-quic-v2 -> https://datatracker.ietf.org/doc/html/rfc9369

I would like to make sure that these drafts do not introduce incompatible changes before ngtcp2 v1 release, which, if happened, we might change ngtcp2 API.  Wait for these draft to finish to avoid this concern.

- [x] Wait for nghttp3 v1 to be released.  We have dependencies on this library.  nghttp3 will be released just before ngtcp2.

## Changes required on v1 release

The following incompatible changes are expected:

- [x] libngtcp2_crypto_openssl will be renamed to libngtcp2_crypto_quictls because OpenSSL has chosen the path not to implement the interface quictls offers and removes the confusion that people wrongly think that the library supports vanilla OpenSSL. examples/client and examples/server are renamed to examples/qtlsclient and examples/qtlsserver respectively. #835 
- [x] NGTCP2_TRANSPORT_PARAMS_V2 macro is removed.  placeholder_field1 and placeholder_field2 fields are removed from ngtcp2_settings.  These are added to make sure that our compatibility mechanism works expectedly. #834 
- [x] The draft QUIC version support is removed. #836 

## Release schedule

- [x] v0.16: regular release as usual
- [x] v0.17: this release should be considered as Release Candidate (RC) 1.
- [x] v0.18: this release should be considered as Release Candidate (RC) 2.
- [x] v0.19: this release should be considered as Release Candidate (RC) 3.
- [x] v1.0.0

RC releases include the changes planned for v1 as described above.
We might release additional RC releases if needed.  After seeing nghttp3 v1 release, we release ngtcp2 v1.

**Comment by tatsuhiro-t** [comment]
https://datatracker.ietf.org/doc/html/rfc9368
https://datatracker.ietf.org/doc/html/rfc9369

**Comment by tatsuhiro-t** [comment]
At the moment, we have no blocking issues for v1.  The next release will be v1, and scheduled for early or mid October.

**Comment by tatsuhiro-t** [comment]
ngtcp2 v1.0.0 is out now.
